apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: manuela-crc-machine-sensor
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sa-mw-dach/manuela-gitops.git
    targetRevision: HEAD
    path: config/instances/manuela-crc/machine-sensor
  destination:
    server: https://kubernetes.default.svc
    namespace: manuela-crc-machine-sensor
  syncPolicy:
    automated: {}
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  - group: route.openshift.io
    kind: Route
    jsonPointers:
    - /status