apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
- route.yaml
bases:
#- github.com/sa-mw-dach/manuela-gitops/config/templates/manuela/messaging
- ../../../templates/manuela-dev/messaging
- ../../../templates/manuela-team-rolebindings
