apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: manuela-argocd-aggregator-client-ocp4

bases:
- ../../../templates/pushprox-client
- ../../../templates/manuela-team-rolebindings

patchesStrategicMerge:
- pushprox-client-deployment.yaml

resources:
- manuela-argocd-aggregator-namespace.yaml
- manuela-argocd-aggregator-operatorgroup.yaml