apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: anomaly-detection
spec:
  tags:
  - name: 0.0.1-12
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-anomaly-detection:0.0.1-12
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.0.1-14
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-anomaly-detection:0.0.1-14
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.0.1-15
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-anomaly-detection:0.0.1-15
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: build-iot-anomaly-0.3.3-1
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-anomaly-detection:build-iot-anomaly-0.3.3-1
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.0.1-20
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-anomaly-detection:0.0.1-20
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.0.1-21
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-anomaly-detection:0.0.1-21
    importPolicy: {}
    referencePolicy:
      type: Local
