apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: anomaly-detection
spec:
  tags:
  - name: 0.3.2-3
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-anomaly-detection:0.3.2-3
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-2
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-anomaly-detection:0.3.2-2
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-1
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-anomaly-detection:0.3.2-1
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-4
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-anomaly-detection:0.3.2-4
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-5
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-anomaly-detection:0.3.2-5
    importPolicy: {}
    referencePolicy:
      type: Local
