apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: anomaly-detection
spec:
  tags:
  - name: 0.3.2-3
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-anomaly-detection:0.3.2-3
<<<<<<< HEAD
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-2
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-anomaly-detection:0.3.2-2
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-1
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-anomaly-detection:0.3.2-1
=======
>>>>>>> ef2ea50ff3f71c1add82fc5e7df6a4a42c5d5472
    importPolicy: {}
    referencePolicy:
      type: Local
      
