apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: anomaly-detection
spec:
  tags:
  - name: 0.3.2-3
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-anomaly-detection:0.3.2-3
    importPolicy: {}
    referencePolicy:
      type: Local
