apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../manuela-openshift/anomaly-detection
patchesStrategicMerge:
- anomaly-detection-is.yaml
images:
- name: anomaly-detection
  newTag: build-iot-anomaly-0.3.3-1
