apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
#- github.com/sa-mw-dach/manuela-gitops/config/templates/manuela/machine-sensor
- ../../../templates/manuela-prod/machine-sensor
- ../../../common/manuela
configMapGenerator:
- name: machine-sensor-1
  behavior: merge
  envs:
   - machine-sensor-1-configmap.properties
- name: machine-sensor-2
  behavior: merge
  envs:
   - machine-sensor-2-configmap.properties
