kind: List
apiVersion: v1
items:
- kind: Secret
  apiVersion: v1
  metadata:
    name: quay-ops-secret
    namespace: manuela-stormshift-messaging
  data:
    .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJiV0Z1ZFdWc1lTdHZjSE02U0UweU16aFdUMDlRTlZGU1VUbE9XVVkzUjFoUFNGTTRWRGRXUTBWT1drcEpWRGxTTjFkRFVGRTBXazlhT0ZoYVMxRllPRFV3V0RnNU5rOHpSRFV4VlE9PSIsCiAgICAgICJlbWFpbCI6ICIiCiAgICB9CiAgfQp9
  type: kubernetes.io/dockerconfigjson
