apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: manuela-bcw-messaging
- apiVersion: operators.coreos.com/v1
  kind: OperatorGroup
  metadata:
    generateName: manuela-bcw-messaging-
    generation: 1
    name: manuela-bcw-messaging
    namespace: manuela-bcw-messaging
  spec:
    targetNamespaces:
    - manuela-bcw-messaging
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: manuela-bcw-messaging
    namespace: argocd
    finalizers:
    - resources-finalizer.argocd.argoproj.io
  spec:
    project: default
    source:
      repoURL: https://github.com/sa-mw-dach/manuela-gitops.git
      targetRevision: HEAD
      path: config/instances/manuela-bcw/messaging
    destination:
      server: https://kubernetes.default.svc
      namespace: manuela-bcw-messaging
    syncPolicy:
      automated: 
        prune: true
        selfHeal: true
    ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
      - /spec/replicas
    - group: route.openshift.io
      kind: Route
      jsonPointers:
      - /status
    - group: image.openshift.io
      kind: ImageStream
      jsonPointers:
      - /spec/tags/0/generation
    - group: apps.openshift.io
      kind: DeploymentConfig
      jsonPointers:
      - /spec/template/spec/containers/0/image