apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: manuela-bcw-machine-sensor
resources:
- machine-sensor-namespace.yaml
bases:
#- github.com/sa-mw-dach/manuela-gitops/config/templates/manuela/machine-sensor
- ../../../templates/manuela-dev/machine-sensor
- ../../../templates/manuela-team-rolebindings
configMapGenerator:
- name: machine-sensor-1
  behavior: merge
  envs:
  - machine-sensor-1-configmap.properties
- name: machine-sensor-2
  behavior: merge
  envs:
  - machine-sensor-2-configmap.properties