apiVersion: v1
kind: ConfigMap
metadata:
  name: machine-sensor-2
data:
  MQTT_HOSTNAME: broker-amq-mqtt-all-0-svc-rte-manuela-crc-messaging.apps-crc.testing
  MQTT_PORT: '80' 
  SENSOR_TEMPERATURE_ENABLED: 'true'
