apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    application: machine-sensor
  name: machine-sensor
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: ImageStreamTag
      name: iot-software-sensor:latest
      namespace: iotdemo
    generation: 2
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source