apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: manuela-stormshift-line-dashboard
resources:
- messaging-namespace.yaml
- messaging-operatorgroup.yaml
patchesStrategicMerge:
- route.yaml
bases:
#- github.com/sa-mw-dach/manuela-gitops/config/templates/manuela/messaging
- ../../../templates/manuela-prod/messaging
- ../../../templates/manuela-team-rolebindings

