apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: manuela-stormshift-messaging
resources:
- messaging-namespace.yaml
- messaging-operatorgroup.yaml

patchesStrategicMerge:
- route.yaml

configMapGenerator:
- name: messaging-configmap
  behavior: merge
  envs:
  - messaging-configmap.properties


bases:
#- github.com/sa-mw-dach/manuela-gitops/config/templates/manuela/messaging
- ../../../templates/manuela-openshift-prod/messaging
- ../../../templates/manuela-openshift-prod/anomaly-detection
- ../../../templates/manuela-team-rolebindings

images:
- name: messaging
  newName: image-registry.openshift-image-registry.svc:5000/manuela-stormshift-messaging/messaging
- name: anomaly-detection
  newName: image-registry.openshift-image-registry.svc:5000/manuela-stormshift-odh/anomaly-detection
