apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: messaging
  name: messaging
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: ImageStreamTag
      name: iot-consumer:latest
      namespace: iotdemo
    generation: 2
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
