apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: messaging
spec:
  triggers:
  - type: ConfigChange
  - type: ImageChange
    imageChangeParams:
      automatic: true
      containerNames:
      - messaging
      from:
        kind: ImageStreamTag
        name: messaging:latest