apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: manuela-tst-all
resources:
- manuela-tst-all-namespace.yaml
- messaging-operatorgroup.yaml

patchesStrategicMerge:
- line-dashboard-route.yaml
- line-dashboard-configmap.yaml
- route.yaml

bases:
- ../../templates/manuela-team-rolebindings

#- github.com/sa-mw-dach/manuela-gitops/config/templates/manuela/line-dashboard
- ../../templates/manuela-dev/line-dashboard

#- github.com/sa-mw-dach/manuela-gitops/config/templates/manuela/messaging
- ../../templates/manuela-dev/messaging

#- github.com/sa-mw-dach/manuela-gitops/config/templates/manuela/machine-sensor
- ../../templates/manuela-dev/machine-sensor


configMapGenerator:
- name: machine-sensor-1
  behavior: merge
  envs: 
    - machine-sensor-1-configmap.properties
- name: machine-sensor-2
  behavior: merge
  envs: 
    - machine-sensor-2-configmap.properties


images:
- name: image-registry.openshift-image-registry.svc:5000/manuela-tst-all/messaging
  newTag: 0.3.2-10
