apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- ../../templates/manuela-team-rolebindings
- ../../templates/manuela-dev/line-dashboard
- ../../templates/manuela-dev/messaging
- ../../templates/manuela-dev/machine-sensor
configMapGenerator:
- behavior: merge
  envs:
  - machine-sensor-1-configmap.properties
  name: machine-sensor-1
- behavior: merge
  envs:
  - machine-sensor-2-configmap.properties
  name: machine-sensor-2
images:
- name: image-registry.openshift-image-registry.svc:5000/manuela-tst-all/messaging
  newTag: 0.3.2-20
kind: Kustomization
namespace: manuela-tst-all
patchesStrategicMerge:
- line-dashboard-route.yaml
- line-dashboard-configmap.yaml
- route.yaml
resources:
- manuela-tst-all-namespace.yaml
- messaging-operatorgroup.yaml
