apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: machine-sensor
spec:
  tags:
  - name: 0.3.1-1
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-software-sensor:0.3.1-1
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-1
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-software-sensor:0.3.1-1
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-1
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-software-sensor:0.3.1-1
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-1
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-software-sensor:0.3.1-1
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-2
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-software-sensor:0.3.1-2
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-1
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-software-sensor:0.3.1-1
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-6
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-software-sensor:0.3.1-6
    importPolicy: {}
    referencePolicy:
      type: Local
