#
# dev branch v3
#
apiVersion: v1
kind: Service
metadata:
  name: mqtt-messaging
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: mqtt-messaging
