apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-4711-comp-0816
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sa-mw-dach/manuela-gitops.git
    targetRevision: HEAD
    path: config/instances/app-4711/comp-0816
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: {}
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  - group: route.openshift.io
    kind: Route
    jsonPointers:
    - /status