apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: messaging
spec:
  tags:
  - name: 0.3.2-5
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-5
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-8
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-8
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-11
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-11
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-12
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-12
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-13
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-13
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-14
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-14
    importPolicy: {}
    referencePolicy:
      type: Local
