apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: messaging
spec:
  tags:
  - name: 0.3.3-28
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.3-28
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-73
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-73
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.3-31
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.3-31
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-1
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-1
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-2
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-2
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-3
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-3
    importPolicy: {}
    referencePolicy:
      type: Local
