apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: messaging
spec:
  tags:
  - name: 0.3.2-2
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-2
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-3
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-3
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-7
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-7
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-9
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-9
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-9
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-9
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-9
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-9
    importPolicy: {}
    referencePolicy:
      type: Local
