apiVersion: v1
kind: ConfigMap
metadata:
  name: service-client-messaging
data:
  host: broker-amq-mqtt-all-0-svc-rte-manuela-stormshift-messaging.apps.ocp3.stormshift.coe.muc.redhat.com
  port: '80' 
